=== akribopo/eXO/eXO/scenarios.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!--
    Document   : scenarios.dtd
    Created on : 2008
    Author     : andy
    Description:
        Purpose of the document follows.

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/scenarios.dtd
-->

<!ELEMENT test (nodes?,scenario*)>

<!ELEMENT nodes EMPTY>
<!ELEMENT scenario (index*,search*,retrieve*,tag*,random_queries*,index_pcontent*,index_user*)>

<!-- SAX PARSER ONLY -->
<!ELEMENT index_pcontent (source,pseydo_file)>
<!ELEMENT index_user (source,user)>

<!-- DOM PARSER -->
<!ELEMENT index (source?,(directory|single_file|pseydo_file|user))>
<!ELEMENT search (source?,query,number_of_results)>
<!ELEMENT retrieve (source?,number_of_results,out_of)>
<!ELEMENT tag (source?,uid,cid,tags)>

<!-- DOM AND SAX -->
<!ELEMENT random_queries (num_type,num_keywords,num_queries,num_results)>

<!ELEMENT source (#PCDATA)>
<!ELEMENT directory (#PCDATA)>
<!ELEMENT single_file (#PCDATA)>
<!ELEMENT pseydo_file (identifier,content_profile)>
<!ELEMENT user (user_address,user_profile)>
<!ELEMENT query (query_type,content)>

<!-- content=0,content_enhanced=1,user=2,user_enhanced=3 -->
<!ELEMENT query_type (#PCDATA)>
<!ELEMENT content (keywords)>

<!-- This is the K of TopK :-)  -->
<!ELEMENT number_of_results (#PCDATA)>
<!ELEMENT out_of (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>

<!ELEMENT user_address (#PCDATA)>
<!ELEMENT user_profile (field*|keywords)>
<!-- This is a number, acts as a name and the checksum is build from this too  -->
<!ELEMENT identifier (#PCDATA)>
<!ELEMENT content_profile (field*|keywords)>

<!ELEMENT field (name,keywords)>
<!ELEMENT name (#PCDATA)>

<!-- Elements of Tag -->
<!ELEMENT uid (#PCDATA)>
<!ELEMENT cid (#PCDATA)>
<!ELEMENT tags (#PCDATA)>


<!-- Elements of Random_Queries -->
<!ELEMENT num_type (#PCDATA)>
<!ELEMENT num_keywords (#PCDATA)>
<!ELEMENT num_queries (#PCDATA)>
<!ELEMENT num_results (#PCDATA)>

=== akribopo/eXO/bin/datasets/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : users.xml
    Created on : October 31, 2008, 4:24 PM
    Author     : andy
    Description:
        Purpose of the document follows.
        Create a set of user profiles and index them around
        the overlay network.
-->

<!DOCTYPE test SYSTEM 'scenarios.dtd'>
<test>
<scenario>
        <index_user>
            <source>1</source>
                <user>
                    <user_address>manos@hotmail.com</user_address>
                    <user_profile>
                        <field>
                            <name>sports</name>
                            <keywords>football bike soccer olympiakos liverpool streetball SEF juventus "Real Madrid"</keywords>
                        </field>
                        <field>
                            <name>music</name>
                            <keywords>alternative rock post-rock rockabily progressive minimal indie jazz classical</keywords>
                        </field>
                        <field>
                            <name>interests</name>
                            <keywords>music painting sports literature</keywords>
                        </field>
                    </user_profile>
                </user>
                
        </index_user>
        <index_user>
            <source>2</source>
                <user>
                    <user_address>antonis@hotmail.com</user_address>
                    <user_profile>
                        <field>
                            <name>sports</name>
                            <keywords>basketball PAO </keywords>
                        </field>
                        <field>
                            <name>music</name>
                            <keywords>Sfakianakis Kinky Tiesto house disco</keywords>
                        </field>
                        <field>
                            <name>interests</name>
                            <keywords>music sports</keywords>
                        </field>
                    </user_profile>
                </user>
                
        </index_user>
        
        <index_user>
            <source>3</source>
                <user>
                    <user_address>katerina@hotmail.com</user_address>
                    <user_profile>
                        <field>
                            <name>dancing</name>
                            <keywords>tango latin salsa</keywords>
                        </field>
                        <field>
                            <name>music</name>
                            <keywords>Paparizou alternative greek mainstream</keywords>
                        </field>
                        <field>
                            <name>interests</name>
                            <keywords>reading dancing surfing</keywords>
                        </field>
                    </user_profile>
                </user>
                
        </index_user>
        
                
        <index_user>
            <source>4</source>
                <user>
                    <user_address>george@hotmail.com</user_address>
                    <user_profile>
                        <field>
                            <name>music</name>
                            <keywords>alternative drum'n'bass rock flamengo tango lounge chillout</keywords>
                        </field>
                        <field>
                            <name>interests</name>
                            <keywords>play guitar surfing </keywords>
                        </field>
                    </user_profile>
                </user>
                
        </index_user>
        
                
        <index_user>
            <source>5</source>
                <user>
                    <user_address>mkos@hotmail.com</user_address>
                    <user_profile>
                        <field>
                            <name>music</name>
                            <keywords>greek oriental mpouzouki art</keywords>
                        </field>
                        <field>
                            <name>interests</name>
                            <keywords>poetry literature philosophy ancient history glossology</keywords>
                        </field>
                    </user_profile>
                </user>
        </index_user>

<random_queries>
        <num_type>2</num_type>
        <num_keywords>2</num_keywords>
        <num_queries>100</num_queries>
        <num_results>10</num_results>
</random_queries>

    </scenario>
</test>

=== akribopo/eXO/eXO/bin/datasets/tags.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : users.xml
    Created on : October 31, 2008, 4:24 PM
    Author     : andy
    Description:
        Purpose of the document follows.
        Create a set of user profiles and tag them around
        the overlay network.
-->

<!DOCTYPE test SYSTEM 'scenarios.dtd'>
<test>
<scenario>

<tag>
<source>28</source>
<uid>2</uid>
<cid>27466598</cid>
<tags>
tagged by andreas
</tags>
</tag>

<tag>
<source>30</source>
<uid>2</uid>
<cid>27566599</cid>
<tags>
stavro
</tags>
</tag>



</scenario>
</test>
